name: Stock Scanner

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22 * * 1-5"
      timezone: "Asia/Kolkata"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Stock Scanner
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python scanner.py
